#!/bin/sh
#
# Create a Alpine based initramfs to be used with Ember VMM
#

set -eu

buildDir=/build
rootfsDir=${buildDir}/rootfs
keepRoot=
# Default as Alpine
flavor=
compress=
addNetwork=1
fcnetPath="/usr/local/bin/fcnet-setup.sh"
initramfsFile="initramfs.cpio"

is_a_container() {
  if [ -f /run/.containerenv ]; then
    # Check env generated by container runtimes
    true
  elif command -v systemd-detect-virt &>/dev/null && systemd-detect-virt -q -c; then
    # Env detected as a container
    true
  elif [ "$$" = "1" ]; then
    # PID of a container is usually 1
    true
  else
    false
  fi
}

main() {
  is_a_container || {
    echo "This needs to be run inside a container!"
    exit 127
    k

    parse_args $@

    case $flavor in
    alpine)
      setup_alpine
      ;;
    *)
      echo "not a valid flavor: $flavor"
      exit 127
      ;;
    esac

    cd $buildDir
    # Delete prev stuff just to be sure
    rm -rf initramfs.img

    if [ -z "$keepRoot" ]; then
      rm -rf "$rootfsDir"
      echo "INFO: building rootfs for flavor: $flavor"

      case $flavor in
      alpine)
        rootfs_alpine
        ;;
      *)
        echo "not a valid flavor: $flavor"
        exit 127
        ;;
      esac

      # set boot and account with symlink
      ln -sf /sbin/init ${rootfsDir}/init
      if [ -n "$addNetwork" ]; then
        setup_ssh_key
        setup_ssh_insecure
      fi
    fi

    echo "INFO: Creating initramfs"
    # create gz'ed cpio?

    if [ -n "$compress" ]; then
      compressor="gzip --best"
    else
      compressor="tee"
    fi

    {cd $rootfsDir
    find . -print0 | cpio --null --create --verbose --format=newc | ${compressor} >${buildDir}/${initramfsFile}
    cd - >/dev/null
  }
  cd - >/dev/null

  echo "INFO: Done!"
}

main $0
exit 0
