[package]
name = "arch"
version.workspace = true
edition.workspace = true

[dependencies]
acpi_tables.workspace = true
remain.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_kv_derive.workspace = true
serde-keyvalue.workspace = true
argh.workspace = true
vm-memory.workspace = true
