[package]
name = "arch"
version.workspace = true
edition.workspace = true

[dependencies]
acpi_tables.workspace = true
remain.workspace = true
anyhow.workspace = true
kvm-bindings.workspace = true
kvm-ioctls.workspace = true
linux-loader.workspace = true
log.workspace = true
vm-memory.workspace = true
